apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-logs
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-logs
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-logs
    spec:
      containers:
        - name: nginx-logs
          image: busybox
          command: [ "sh", "-c", "tail -f /var/log/nginx/**/*.log" ]
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: '0.1'
              memory: 128M
            limits:
              cpu: '0.2'
              memory: 128M
          volumeMounts:
            - name: nginx-logs
              mountPath: /var/log/nginx
      volumes:
        - name: nginx-logs
          hostPath:
            path: /var/log/nginx
      # Configure the server where the nginx are
      # tolerations:
      #   - key: "environment"
      #     operator: "Equal"
      #     value: "master"
      #     effect: "NoSchedule"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: "node-role.kubernetes.io/master"
      #           operator: "In"
      #           values:
      #           - "true"
