apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-nginx
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: geolocation-nginx
    spec:
      containers:
        - name: geolocation-nginx
          image: hagendev/get-ip-nginx:latest
          command: [ "python3", "ip_nginx.py" ]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '0.1'
              memory: 128M
            limits:
              cpu: '0.2'
              memory: 256M
          envFrom:
            - secretRef:
                name: geolocation-nginx
          volumeMounts:
            - name: geolocation-nginx
              mountPath: /var/log/nginx
      volumes:
        - name: geolocation-nginx
          hostPath:
            path: /var/log/nginx
      imagePullSecrets:
        - name: docker-secret
      # Configure the server where the nginx are
      # tolerations:
      #   - key: "environment"
      #     operator: "Equal"
      #     value: "nginx"
      #     effect: "NoSchedule"
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: "node-role.kubernetes.io/master"
      #           operator: "In"
      #           values:
      #           - "true"
