apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres
  resources:
    requests:
      storage: 10Gi
  volumeName: postgres
