apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-monitoring
  namespace: monitoring
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
