apiVersion: v1
kind: Service
metadata:
  name: postgres-monitoring
  namespace: monitoring
spec:
  selector:
    app: postgres-monitoring
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 32103
  type: NodePort
