apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres
  hostPath:
    path: /srv/databases/postgres
  volumeMode: Filesystem
