apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: '0.1'
              memory: 128Mi
            limits:
              cpu: '0.3'
              memory: 512Mi
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
      # tolerations:
      #   - key: environment
      #     operator: Equal
      #     value: database
      #     effect: NoSchedule
