apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: monitoring
type: Opaque
data:
  POSTGRES_USER: dWNhbnRhdXRoNjk=
  POSTGRES_PASSWORD: dWNhbnRhdXRoNjk=
  POSTGRES_DB: dWNhbnRhdXRoNjk=
