apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-monitoring
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-monitoring
  resources:
    requests:
      storage: 10Gi
  volumeName: postgres-monitoring
